In [70]:
exec(open('file_reader.py').read())

generating features..

 553480082996879360

 581153923987206146

 500298588992593920

 552788945017516032

 524948206023880704

 553561170637238272

 758159624122097664

 767725956706414592

 580352273001410560

 581359544682614784

 763098277986209792

 581290271997968384

 775057555865206784

 500280249629036544

 498293668655423488

 774991078265094144

 553553288625672192

 524961721744900097

 524941720249978880

 544294893146091520

 768859780240773121

 764927075522260992

 544274544174071809

 498486826269548545

 544315472075042818

 524923293711998976

 769988636754505729

 524936793633083394

 553480082996879360

 581153923987206146

 500298588992593920

 552788945017516032

 524948206023880704

 553561170637238272

 758159624122097664

 767725956706414592

 580352273001410560

 581359544682614784

 763098277986209792

 581290271997968384

 775057555865206784

 500280249629036544

 498293668655423488

 774991078265094144

 553553288625672192

 524961721744900097

 5249417202

In [71]:
df.head()


classification context_path has_context  \
580319078155468800           true          NaN           0   
580319184652890113          false          NaN           0   
580320684305416192     unverified          NaN           0   
580321156508577792          false          NaN           0   
580322453928431617          false          NaN           0   

                                                                 text  \
580319078155468800  Germanwings Airbus A320 crashes in French Alps...   
580319184652890113  BREAKING: 148 passengers were on board #German...   
580320684305416192  Accident aircraft looks to be Germanwings (Air...   
580321156508577792  Now hearing 148 passengers + crew on board the...   
580322453928431617  German Wings airline tweeting now about report...   

                         topic  opinion  
580319078155468800        true        0  
580319184652890113       false        0  
580320684305416192  unverified        0  
580321156508577792       false        0  
580322453928431617       false        0

In [72]:
import sys
sys.path.insert(1, "./feature-extraction/twitter-features")
from VulgarExtractor import VulgarExtractor

In [73]:
wordlist = VulgarExtractor.vulgarWords("badwords.txt") 
dftext = df[['text']]
result = dftext.applymap(lambda x: VulgarExtractor.containsVulgar(x,wordlist))
df['isVulgar'] = result
df.head()

classification context_path has_context  \
580319078155468800           true          NaN           0   
580319184652890113          false          NaN           0   
580320684305416192     unverified          NaN           0   
580321156508577792          false          NaN           0   
580322453928431617          false          NaN           0   

                                                                 text  \
580319078155468800  Germanwings Airbus A320 crashes in French Alps...   
580319184652890113  BREAKING: 148 passengers were on board #German...   
580320684305416192  Accident aircraft looks to be Germanwings (Air...   
580321156508577792  Now hearing 148 passengers + crew on board the...   
580322453928431617  German Wings airline tweeting now about report...   

                         topic  opinion  isVulgar  
580319078155468800        true        0     False  
580319184652890113       false        0     False  
580320684305416192  unverified        0     False  
580321156508577792       false        0     False  
580322453928431617       false        0     False

In [74]:
from TwitterParser import TwitterParser
textlist = [txt.replace('\n','') for txt in df['text'].tolist()]
tagged_sents = TwitterParser.tag(textlist)
print(len(tagged_sents))
df['POS'] = tagged_sents
df

25


classification  \
580319078155468800           true   
580319184652890113          false   
580320684305416192     unverified   
580321156508577792          false   
580322453928431617          false   
580323060533764097           true   
580324027715063808           true   
580325090367315968     unverified   
580326222107951104          false   
580331561398108160          false   
580332109782466561           true   
580333763512705025          false   
580333909008871424           true   
580339547269144576          false   
580339825649291264          false   
580340476949086208          false   
580348081100734464           true   
580360165540642816          false   
580371845997682688           true   
580882341880446977           true   
581047170637381632           true   
581063377226637312           true   
581293286268129280          false   
581386094337474560     unverified   
581473088249958400          false   

                                                         context_path  \
580319078155468800                                                NaN   
580319184652890113                                                NaN   
580320684305416192                                                NaN   
580321156508577792                                                NaN   
580322453928431617                                                NaN   
580323060533764097                                                NaN   
580324027715063808  ./semeval2017-task8-dataset/rumoureval-data/ge...   
580325090367315968  ./semeval2017-task8-dataset/rumoureval-data/ge...   
580326222107951104  ./semeval2017-task8-dataset/rumoureval-data/ge...   
580331561398108160  ./semeval2017-task8-dataset/rumoureval-data/ge...   
580332109782466561  ./semeval2017-task8-dataset/rumoureval-data/ge...   
580333763512705025  ./semeval2017-task8-dataset/rumoureval-data/ge...   
580333909008871424  ./semeval2017-task8-dataset/rumoureval-data/ge...   
580339547269144576  ./semeval2017-task8-dataset/rumoureval-data/ge...   
580339825649291264  ./semeval2017-task8-dataset/rumoureval-data/ge...   
580340476949086208  ./semeval2017-task8-dataset/rumoureval-data/ge...   
580348081100734464  ./semeval2017-task8-dataset/rumoureval-data/ge...   
580360165540642816  ./semeval2017-task8-dataset/rumoureval-data/ge...   
580371845997682688  ./semeval2017-task8-dataset/rumoureval-data/ge...   
580882341880446977  ./semeval2017-task8-dataset/rumoureval-data/ge...   
581047170637381632  ./semeval2017-task8-dataset/rumoureval-data/ge...   
581063377226637312  ./semeval2017-task8-dataset/rumoureval-data/ge...   
581293286268129280  ./semeval2017-task8-dataset/rumoureval-data/ge...   
581386094337474560  ./semeval2017-task8-dataset/rumoureval-data/ge...   
581473088249958400  ./semeval2017-task8-dataset/rumoureval-data/ge...   

                   has_context  \
580319078155468800           0   
580319184652890113           0   
580320684305416192           0   
580321156508577792           0   
580322453928431617           0   
580323060533764097           0   
580324027715063808           1   
580325090367315968           1   
580326222107951104           1   
580331561398108160           1   
580332109782466561           1   
580333763512705025           1   
580333909008871424           1   
580339547269144576           1   
580339825649291264           1   
580340476949086208           1   
580348081100734464           1   
580360165540642816           1   
580371845997682688           1   
580882341880446977           1   
581047170637381632           1   
581063377226637312           1   
581293286268129280           1   
581386094337474560           1   
581473088249958400           1   

                                                                 text  \
580319078155468800  Germanwings Airbus A320 crashes in French Alps...   
580319184652890113  BREAKING: 148 passengers were on board #German...   
580320684305416192  Accident aircraft looks to be Ger

In [75]:
word_counts = [TwitterParser.word_count(tagged_line) for tagged_line in df['POS']]
pos_count_list = [TwitterParser.pos_counts(tagged_line) for tagged_line in df['POS']]
contains_adjs = [TwitterParser.contains_adjectives(tagged_line) for tagged_line in df['POS']]
contains_urls = [TwitterParser.contains_url(tagged_line) for tagged_line in df['POS']]
contains_emojis = [TwitterParser.contains_emoji(tagged_line) for tagged_line in df['POS']]
contains_abbrevs = [TwitterParser.contains_abbreviation(tagged_line) for tagged_line in df['POS']]

df['wordCount'] = word_counts
df['posCounts'] = pos_count_list
df['containsAdjective'] = contains_adjs
df['containsURL'] = contains_urls
df['containsEmoji'] = contains_emojis
df['containsAbbreviation'] = contains_abbrevs
df

classification  \
580319078155468800           true   
580319184652890113          false   
580320684305416192     unverified   
580321156508577792          false   
580322453928431617          false   
580323060533764097           true   
580324027715063808           true   
580325090367315968     unverified   
580326222107951104          false   
580331561398108160          false   
580332109782466561           true   
580333763512705025          false   
580333909008871424           true   
580339547269144576          false   
580339825649291264          false   
580340476949086208          false   
580348081100734464           true   
580360165540642816          false   
580371845997682688           true   
580882341880446977           true   
581047170637381632           true   
581063377226637312           true   
581293286268129280          false   
581386094337474560     unverified   
581473088249958400          false   

                                                         context_path  \
580319078155468800                                                NaN   
580319184652890113                                                NaN   
580320684305416192                                                NaN   
580321156508577792                                                NaN   
580322453928431617                                                NaN   
580323060533764097                                                NaN   
580324027715063808  ./semeval2017-task8-dataset/rumoureval-data/ge...   
580325090367315968  ./semeval2017-task8-dataset/rumoureval-data/ge...   
580326222107951104  ./semeval2017-task8-dataset/rumoureval-data/ge...   
580331561398108160  ./semeval2017-task8-dataset/rumoureval-data/ge...   
580332109782466561  ./semeval2017-task8-dataset/rumoureval-data/ge...   
580333763512705025  ./semeval2017-task8-dataset/rumoureval-data/ge...   
580333909008871424  ./semeval2017-task8-dataset/rumoureval-data/ge...   
580339547269144576  ./semeval2017-task8-dataset/rumoureval-data/ge...   
580339825649291264  ./semeval2017-task8-dataset/rumoureval-data/ge...   
580340476949086208  ./semeval2017-task8-dataset/rumoureval-data/ge...   
580348081100734464  ./semeval2017-task8-dataset/rumoureval-data/ge...   
580360165540642816  ./semeval2017-task8-dataset/rumoureval-data/ge...   
580371845997682688  ./semeval2017-task8-dataset/rumoureval-data/ge...   
580882341880446977  ./semeval2017-task8-dataset/rumoureval-data/ge...   
581047170637381632  ./semeval2017-task8-dataset/rumoureval-data/ge...   
581063377226637312  ./semeval2017-task8-dataset/rumoureval-data/ge...   
581293286268129280  ./semeval2017-task8-dataset/rumoureval-data/ge...   
581386094337474560  ./semeval2017-task8-dataset/rumoureval-data/ge...   
581473088249958400  ./semeval2017-task8-dataset/rumoureval-data/ge...   

                   has_context  \
580319078155468800           0   
580319184652890113           0   
580320684305416192           0   
580321156508577792           0   
580322453928431617           0   
580323060533764097           0   
580324027715063808           1   
580325090367315968           1   
580326222107951104           1   
580331561398108160           1   
580332109782466561           1   
580333763512705025           1   
580333909008871424           1   
580339547269144576           1   
580339825649291264           1   
580340476949086208           1   
580348081100734464           1   
580360165540642816           1   
580371845997682688           1   
580882341880446977           1   
581047170637381632           1   
581063377226637312           1   
581293286268129280           1   
581386094337474560           1   
581473088249958400           1   

                                                                 text  \
580319078155468800  Germanwings Airbus A320 crashes in French Alps...   
580319184652890113  BREAKING: 148 passengers were on board #German...   
580320684305416192  Accident aircraft looks to be Ger

In [89]:
for i, tag in enumerate(TwitterParser.tagset):
    tag_counts = []
    for pos_counts in df['posCounts']:
        tag_counts.append(pos_counts[i])
    column_name = 'num_' + tag
    df[column_name] = tag_counts
df.head()

classification context_path has_context  \
580319078155468800              1          NaN           0   
580319184652890113              0          NaN           0   
580320684305416192              2          NaN           0   
580321156508577792              0          NaN           0   
580322453928431617              0          NaN           0   

                                                                 text  \
580319078155468800  Germanwings Airbus A320 crashes in French Alps...   
580319184652890113  BREAKING: 148 passengers were on board #German...   
580320684305416192  Accident aircraft looks to be Germanwings (Air...   
580321156508577792  Now hearing 148 passengers + crew on board the...   
580322453928431617  German Wings airline tweeting now about report...   

                         topic  opinion  isVulgar  \
580319078155468800        true        0     False   
580319184652890113       false        0     False   
580320684305416192  unverified        0     False   
580321156508577792       false        0     False   
580322453928431617       false        0     False   

                                                                  POS  \
580319078155468800  [(Germanwings, ^), (Airbus, ^), (A320, ^), (cr...   
580319184652890113  [(BREAKING, N), (:, ,), (148, $), (passengers,...   
580320684305416192  [(Accident, N), (aircraft, N), (looks, V), (to...   
580321156508577792  [(Now, R), (hearing, V), (148, $), (passengers...   
580322453928431617  [(German, A), (Wings, N), (airline, N), (tweet...   

                    wordCount  \
580319078155468800         10   
580319184652890113         17   
580320684305416192         17   
580321156508577792         18   
580322453928431617         18   

                                                            posCounts  ...    \
580319078155468800  [0, 0, 0, 7, 0, 0, 0, 1, 0, 0, 0, 0, 2, 0, 0, ...  ...     
580319184652890113  [3, 0, 0, 5, 0, 0, 0, 3, 1, 0, 0, 2, 2, 0, 0, ...  ...     
580320684305416192  [6, 0, 0, 4, 0, 0, 0, 2, 0, 0, 0, 0, 2, 1, 0, ...  ...     
580321156508577792  [4, 0, 0, 2, 0, 0, 0, 3, 1, 1, 0, 1, 3, 1, 0, ...  ...     
580322453928431617  [6, 0, 0, 2, 0, 0, 0, 2, 1, 1, 0, 0, 5, 0, 0, ...  ...     

                    num_X  num_Y  num_#  num_@  num_~  num_U  num_E  num_$  \
580319078155468800      0      0      0      0      0      0      0      0   
580319184652890113      0      0      1      0      0      0      0      1   
580320684305416192      0      0      1      0      0      0      0      2   
580321156508577792      0      0      1      1      0      0      0      2   
580322453928431617      0      0      0      1      0      0      0      1   

                    num_,  num_G  
580319078155468800      0      0  
580319184652890113      1      0  
580320684305416192      4      0  
580321156508577792      2      0  
580322453928431617      1      0  

[5 rows x 39 columns]

In [110]:

df.loc[df.classification == 'true', 'classification'] = 1
df.loc[df.classification == 'false', 'classification'] = 0
df.loc[df.classification == 'unverified', 'classification'] = 2


attributes = []
# getting the labels
# You have to comment this out if you want only tweet ID to be in the features. 
# Note that by doing this, you will screw up the simple/tr,simple/dev test located after this
attributes = ['isVulgar', 'containsAdjective', 'containsURL', 'containsEmoji', 'containsAbbreviation']

dev_labels = df['classification']
dev_labels = [l for l in labels]
dev_labels = np.array(labels)

# getting the values as a list of lists
dev_values = df[attributes].values.tolist()


#Below puts the tweet ID as a feature. Comment this out if you aren't using tweetID
###for i,index in enumerate(df.index):
###    dev_values[i].append(int(index))


dev_values = np.array(dev_values)
dev_values

array([[False, False, False, False, False],
       [False,  True, False, False, False],
       [False, False, False, False, False],
       [False,  True, False, False, False],
       [False,  True, False, False, False],
       [False, False, False, False, False],
       [False,  True, False, False, False],
       [False,  True, False, False,  True],
       [False, False, False, False, False],
       [False, False, False, False,  True],
       [ True,  True, False, False, False],
       [False,  True, False, False, False],
       [False, False, False, False,  True],
       [False,  True, False, False, False],
       [False,  True, False, False, False],
       [False,  True, False, False, False],
       [False,  True, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False,  True, False, False, False],
       [False,  True, False, False, False],
       [False, False, False, False, False],
       [False,  True, False, Fal

In [111]:
import classifiers

# note predict_proba() gets probabilities for all 3 labels
#... and decision_tree_classifier uses decision_function() instead of predict_proba()... weird sklearn quirk
# NOTE: This is where you change the classifier type. Can pick from [naive_bayes, svm_classifier, decision_tree_classifier]
predictions, probabilities = classifiers.naive_bayes(dev_values, dev_labels, dev_values)

ps = []
for i, p in enumerate(predictions):
    if p == 0:
        ps.append('false')
    if p == 1:
        ps.append('true')
    if p == 2:
        ps.append('unverified')
    

# creates pairings of the prediction and the probability of the prediction
pred_probs_pairs = [[ps[i], probabilities[i][predictions[i]]] for i in range(len(predictions))]  

#now we make a dictionary of tweetID to the pred_probs_pairs
pred_dict = {index:pred_probs_pairs[i] for i,index in enumerate(df.index)}
pred_dict



{'580319078155468800': ['false', 0.85455877190299756],
 '580319184652890113': ['false', 0.85459043791595524],
 '580320684305416192': ['false', 0.85455877190299756],
 '580321156508577792': ['false', 0.85459043791595524],
 '580322453928431617': ['false', 0.85459043791595524],
 '580323060533764097': ['false', 0.85455877190299756],
 '580324027715063808': ['false', 0.85459043791595524],
 '580325090367315968': ['false', 0.5302855069870045],
 '580326222107951104': ['false', 0.85455877190299756],
 '580331561398108160': ['false', 0.53028392857380202],
 '580332109782466561': ['true', 1.0],
 '580333763512705025': ['false', 0.85459043791595524],
 '580333909008871424': ['false', 0.53028392857380202],
 '580339547269144576': ['false', 0.85459043791595524],
 '580339825649291264': ['false', 0.85459043791595524],
 '580340476949086208': ['false', 0.85459043791595524],
 '580348081100734464': ['false', 0.85459043791595524],
 '580360165540642816': ['false', 0.85455877190299756],
 '580371845997682688': ['fal

In [112]:
with open('output/classifier_output/test.json', 'w') as outfile:
    json.dump(pred_dict, outfile)

In [113]:
## python3 scorer/score.py semeval2017-task8-dataset/traindev/rumoureval-subtaskB-dev.json output/classifier_output/test.json



## Training on simple/tr, testing on simple/dev

In [114]:
# Simply doing all of the transformations we did in the first few cells

tr_df = pd.read_pickle('output/simple/train_data_simple.pickle')

wordlist = VulgarExtractor.vulgarWords("badwords.txt") 
dftext = tr_df[['text']]
result = dftext.applymap(lambda x: VulgarExtractor.containsVulgar(x,wordlist))
tr_df['isVulgar'] = result

sys.path.insert(1, "./feature-extraction/twitter-features")
textlist = [txt.replace('\n','') for txt in tr_df['text'].tolist()]
tagged_sents = TwitterParser.tag(textlist)
tr_df['POS'] = tagged_sents

word_counts = [TwitterParser.word_count(tagged_line) for tagged_line in tr_df['POS']]
pos_count_list = [TwitterParser.pos_counts(tagged_line) for tagged_line in tr_df['POS']]
contains_adjs = [TwitterParser.contains_adjectives(tagged_line) for tagged_line in tr_df['POS']]
contains_urls = [TwitterParser.contains_url(tagged_line) for tagged_line in tr_df['POS']]
contains_emojis = [TwitterParser.contains_emoji(tagged_line) for tagged_line in tr_df['POS']]
contains_abbrevs = [TwitterParser.contains_abbreviation(tagged_line) for tagged_line in tr_df['POS']]

tr_df['wordCount'] = word_counts
tr_df['posCounts'] = pos_count_list
tr_df['containsAdjective'] = contains_adjs
tr_df['containsURL'] = contains_urls
tr_df['containsEmoji'] = contains_emojis
tr_df['containsAbbreviation'] = contains_abbrevs

for i, tag in enumerate(TwitterParser.tagset):
    tag_counts = []
    for pos_counts in tr_df['posCounts']:
        tag_counts.append(pos_counts[i])
    column_name = 'num_' + tag
    tr_df[column_name] = tag_counts

tr_df.head()

classification  \
498280126254428160     unverified   
498430783699554305           true   
499366666300846081     unverified   
499368931367608320     unverified   
499456140044824576     unverified   

                                                         context_path  \
498280126254428160                                                NaN   
498430783699554305                                                NaN   
499366666300846081                                                NaN   
499368931367608320                                                NaN   
499456140044824576  ./semeval2017-task8-dataset/rumoureval-data/fe...   

                   has_context  \
498280126254428160           0   
498430783699554305           0   
499366666300846081           0   
499368931367608320           0   
499456140044824576           1   

                                                                 text  \
498280126254428160  Mike Brown was staying with his grandmother fo...   
498430783699554305  Witness: Police allegedly stopped Mike Brown a...   
499366666300846081  Line of police cars with high beams on greets ...   
499368931367608320  Currently the #FoxNews website has zero, repea...   
499456140044824576  St. Louis Co Police tell me ofcr shot a man wh...   

                       topic  isVulgar  \
498280126254428160  ferguson     False   
498430783699554305  ferguson     False   
499366666300846081  ferguson     False   
499368931367608320  ferguson     False   
499456140044824576  ferguson     False   

                                                                  POS  \
498280126254428160  [(Mike, ^), (Brown, ^), (was, V), (staying, V)...   
498430783699554305  [(Witness, N), (:, ,), (Police, N), (allegedly...   
499366666300846081  [(Line, N), (of, P), (police, N), (cars, N), (...   
499368931367608320  [(Currently, R), (the, D), (#FoxNews, ^), (web...   
499456140044824576  [(St., ^), (Louis, ^), (Co, ^), (Police, ^), (...   

                    wordCount  \
498280126254428160         15   
498430783699554305         14   
499366666300846081         20   
499368931367608320         20   
499456140044824576         26   

                                                            posCounts  \
498280126254428160  [3, 1, 0, 2, 0, 0, 0, 3, 0, 0, 0, 3, 3, 0, 0, ...   
498430783699554305  [3, 1, 0, 2, 0, 0, 0, 3, 0, 1, 0, 0, 4, 0, 0, ...   
499366666300846081  [6, 0, 0, 1, 0, 1, 0, 5, 1, 0, 0, 1, 4, 0, 1, ...   
499368931367608320  [7, 0, 0, 3, 0, 0, 0, 1, 1, 2, 0, 2, 3, 0, 0, ...   
499456140044824576  [5, 3, 0, 6, 0, 0, 0, 2, 2, 0, 0, 1, 5, 1, 0, ...   

                    containsAdjective  ...    num_X  num_Y  num_#  num_@  \
498280126254428160              False  ...        0      0      1      0   
498430783699554305              False  ...        0      0      1      0   
499366666300846081               True  ...        0      0      0      0   
499368931367608320               True  ...        0      0      0      0   
499456140044824576               True  ...        0      0      1      0   

                    num_~  num_U  num_E  num_$  num_,  num_G  
498280126254428160      0      0      0      0      2      0  
498430783699554305      0      1      0      0      2      0  
499366666300846081      0      1      0      0      3      0  
499368931367608320      0      0      0      1      4      0  
499456140044824576      0      0      0      1      1      0  

[5 rows x 38 columns]

In [115]:
# Changes "true"/"false"/"unverified" to numeric values, just like the in the early cells

tr_df.loc[tr_df.classification == 'true', 'classification'] = 1
tr_df.loc[tr_df.classification == 'false', 'classification'] = 0
tr_df.loc[tr_df.classification == 'unverified', 'classification'] = 2
# getting the labels

attributes = ['isVulgar', 'containsAdjective', 'containsURL', 'containsEmoji', 'containsAbbreviation']


tr_labels = tr_df['classification']
tr_labels = [l for l in tr_labels]
tr_labels = np.array(tr_labels)


# getting the values as a list of lists
tr_values = tr_df[attributes].values.tolist()
tr_values = np.array(tr_values)


In [116]:
predictions, probabilities = classifiers.decision_tree_classifier(tr_values, tr_labels, dev_values)
print(probabilities)
ps = []
for i, p in enumerate(predictions):
    if p == 0:
        ps.append('false')
    if p == 1:
        ps.append('true')
    if p == 2:
        ps.append('unverified')
    

# creates pairings of the prediction and the probability of the prediction
pred_probs_pairs = [[ps[i], probabilities[i][predictions[i]]] for i in range(len(predictions))]  


pred_dict = {index:pred_probs_pairs[i] for i,index in enumerate(df.index)}


pred_dict


[[ 0.17647059  0.44117647  0.38235294]
 [ 0.15384615  0.36538462  0.48076923]
 [ 0.17647059  0.44117647  0.38235294]
 [ 0.15384615  0.36538462  0.48076923]
 [ 0.15384615  0.36538462  0.48076923]
 [ 0.17647059  0.44117647  0.38235294]
 [ 0.15384615  0.36538462  0.48076923]
 [ 0.          1.          0.        ]
 [ 0.17647059  0.44117647  0.38235294]
 [ 0.          1.          0.        ]
 [ 0.          0.          1.        ]
 [ 0.15384615  0.36538462  0.48076923]
 [ 0.          1.          0.        ]
 [ 0.15384615  0.36538462  0.48076923]
 [ 0.15384615  0.36538462  0.48076923]
 [ 0.15384615  0.36538462  0.48076923]
 [ 0.15384615  0.36538462  0.48076923]
 [ 0.17647059  0.44117647  0.38235294]
 [ 0.17647059  0.44117647  0.38235294]
 [ 0.15384615  0.36538462  0.48076923]
 [ 0.15384615  0.36538462  0.48076923]
 [ 0.17647059  0.44117647  0.38235294]
 [ 0.15384615  0.36538462  0.48076923]
 [ 0.15384615  0.36538462  0.48076923]
 [ 0.          1.          0.        ]]


{'580319078155468800': ['true', 0.44117647058823528],
 '580319184652890113': ['unverified', 0.48076923076923078],
 '580320684305416192': ['true', 0.44117647058823528],
 '580321156508577792': ['unverified', 0.48076923076923078],
 '580322453928431617': ['unverified', 0.48076923076923078],
 '580323060533764097': ['true', 0.44117647058823528],
 '580324027715063808': ['unverified', 0.48076923076923078],
 '580325090367315968': ['true', 1.0],
 '580326222107951104': ['true', 0.44117647058823528],
 '580331561398108160': ['true', 1.0],
 '580332109782466561': ['unverified', 1.0],
 '580333763512705025': ['unverified', 0.48076923076923078],
 '580333909008871424': ['true', 1.0],
 '580339547269144576': ['unverified', 0.48076923076923078],
 '580339825649291264': ['unverified', 0.48076923076923078],
 '580340476949086208': ['unverified', 0.48076923076923078],
 '580348081100734464': ['unverified', 0.48076923076923078],
 '580360165540642816': ['true', 0.44117647058823528],
 '580371845997682688': ['true', 

In [117]:
with open('output/classifier_output/tr_test.json', 'w') as outfile:
    json.dump(pred_dict, outfile)
    
#test with:
### python3 scorer/score.py semeval2017-task8-dataset/traindev/rumoureval-subtaskB-dev.json output/classifier_output/tr_test.json