In [1]:
exec(open('file_reader.py').read())
df.head()

generating features..

 553480082996879360

 581153923987206146

 500298588992593920

 552788945017516032

 524948206023880704

 553561170637238272

 758159624122097664

 767725956706414592

 580352273001410560

 581359544682614784

 763098277986209792

 581290271997968384

 775057555865206784

 500280249629036544

 498293668655423488

 774991078265094144

 553553288625672192

 524961721744900097

 524941720249978880

 544294893146091520

 768859780240773121

 764927075522260992

 544274544174071809

 498486826269548545

 544315472075042818

 524923293711998976

 769988636754505729

 524936793633083394

 553480082996879360

 581153923987206146

 500298588992593920

 552788945017516032

 524948206023880704

 553561170637238272

 758159624122097664

 767725956706414592

 580352273001410560

 581359544682614784

 763098277986209792

 581290271997968384

 775057555865206784

 500280249629036544

 498293668655423488

 774991078265094144

 553553288625672192

 524961721744900097

 5249417202

classification context_path has_context  \
580319078155468800           true          NaN           0   
580319184652890113          false          NaN           0   
580320684305416192     unverified          NaN           0   
580321156508577792          false          NaN           0   
580322453928431617          false          NaN           0   

                                                                 text  \
580319078155468800  Germanwings Airbus A320 crashes in French Alps...   
580319184652890113  BREAKING: 148 passengers were on board #German...   
580320684305416192  Accident aircraft looks to be Germanwings (Air...   
580321156508577792  Now hearing 148 passengers + crew on board the...   
580322453928431617  German Wings airline tweeting now about report...   

                         topic  opinion  
580319078155468800        true        0  
580319184652890113       false        0  
580320684305416192  unverified        0  
580321156508577792       false        0  
580322453928431617       false        0

In [2]:
import sys
sys.path.insert(1, "./feature-extraction/twitter-features")
from VulgarExtractor import VulgarExtractor

In [3]:
wordlist = VulgarExtractor.vulgarWords("badwords.txt") 
dftext = df[['text']]
result = dftext.applymap(lambda x: VulgarExtractor.containsVulgar(x,wordlist))
df['isVulgar'] = result
df.head()

classification context_path has_context  \
580319078155468800           true          NaN           0   
580319184652890113          false          NaN           0   
580320684305416192     unverified          NaN           0   
580321156508577792          false          NaN           0   
580322453928431617          false          NaN           0   

                                                                 text  \
580319078155468800  Germanwings Airbus A320 crashes in French Alps...   
580319184652890113  BREAKING: 148 passengers were on board #German...   
580320684305416192  Accident aircraft looks to be Germanwings (Air...   
580321156508577792  Now hearing 148 passengers + crew on board the...   
580322453928431617  German Wings airline tweeting now about report...   

                         topic  opinion  isVulgar  
580319078155468800        true        0     False  
580319184652890113       false        0     False  
580320684305416192  unverified        0     False  
580321156508577792       false        0     False  
580322453928431617       false        0     False

In [4]:
from TwitterParser import TwitterParser
textlist = [txt.replace('\n','') for txt in df['text'].tolist()]
tagged_sents = TwitterParser.tag(textlist)
df['POS'] = tagged_sents
df.head()

classification context_path has_context  \
580319078155468800           true          NaN           0   
580319184652890113          false          NaN           0   
580320684305416192     unverified          NaN           0   
580321156508577792          false          NaN           0   
580322453928431617          false          NaN           0   

                                                                 text  \
580319078155468800  Germanwings Airbus A320 crashes in French Alps...   
580319184652890113  BREAKING: 148 passengers were on board #German...   
580320684305416192  Accident aircraft looks to be Germanwings (Air...   
580321156508577792  Now hearing 148 passengers + crew on board the...   
580322453928431617  German Wings airline tweeting now about report...   

                         topic  opinion  isVulgar  \
580319078155468800        true        0     False   
580319184652890113       false        0     False   
580320684305416192  unverified        0     False   
580321156508577792       false        0     False   
580322453928431617       false        0     False   

                                                                  POS  
580319078155468800  [(Germanwings, ^), (Airbus, ^), (A320, ^), (cr...  
580319184652890113  [(BREAKING, N), (:, ,), (148, $), (passengers,...  
580320684305416192  [(Accident, N), (aircraft, N), (looks, V), (to...  
580321156508577792  [(Now, R), (hearing, V), (148, $), (passengers...  
580322453928431617  [(German, A), (Wings, N), (airline, N), (tweet...

In [5]:
processed_sents = []
for tagged_sent in df['POS']:
    processed_words = []
    for word, tag in tagged_sent:
        if tag == 'U':
            processed_words.append('someurl')
        elif tag == '@':
            processed_words.append('@someuser')
        else:
            processed_words.append(word)
    sent = ' '.join(processed_words)
    processed_sents.append(sent)
df['text'] = processed_sents

In [6]:
df.head()

classification context_path has_context  \
580319078155468800           true          NaN           0   
580319184652890113          false          NaN           0   
580320684305416192     unverified          NaN           0   
580321156508577792          false          NaN           0   
580322453928431617          false          NaN           0   

                                                                 text  \
580319078155468800  Germanwings Airbus A320 crashes in French Alps...   
580319184652890113  BREAKING : 148 passengers were on board #Germa...   
580320684305416192  Accident aircraft looks to be Germanwings ( Ai...   
580321156508577792  Now hearing 148 passengers + crew on board the...   
580322453928431617  German Wings airline tweeting now about report...   

                         topic  opinion  isVulgar  \
580319078155468800        true        0     False   
580319184652890113       false        0     False   
580320684305416192  unverified        0     False   
580321156508577792       false        0     False   
580322453928431617       false        0     False   

                                                                  POS  
580319078155468800  [(Germanwings, ^), (Airbus, ^), (A320, ^), (cr...  
580319184652890113  [(BREAKING, N), (:, ,), (148, $), (passengers,...  
580320684305416192  [(Accident, N), (aircraft, N), (looks, V), (to...  
580321156508577792  [(Now, R), (hearing, V), (148, $), (passengers...  
580322453928431617  [(German, A), (Wings, N), (airline, N), (tweet...

In [7]:
def normalize(column_name):
    std = df[column_name].std()
    norm_col = df[column_name].apply(lambda x: x - std)
    df[column_name] = norm_col

In [8]:
# import TwitterParser features
word_counts = [TwitterParser.word_count(tagged_line) for tagged_line in df['POS']]
pos_count_list = [TwitterParser.pos_counts(tagged_line) for tagged_line in df['POS']]
contains_adjs = [TwitterParser.contains_adjectives(tagged_line) for tagged_line in df['POS']]
contains_urls = [TwitterParser.contains_url(tagged_line) for tagged_line in df['POS']]
contains_emojis = [TwitterParser.contains_emoji(tagged_line) for tagged_line in df['POS']]
contains_abbrevs = [TwitterParser.contains_abbreviation(tagged_line) for tagged_line in df['POS']]

# get word count and normalize
df['wordCount'] = word_counts
normalize('wordCount')

# get an indexed list of pos tag counts
df['posCounts'] = pos_count_list

# get binary features
df['containsAdjective'] = contains_adjs
df['containsURL'] = contains_urls
df['containsEmoji'] = contains_emojis
df['containsAbbreviation'] = contains_abbrevs

df.head()

classification context_path has_context  \
580319078155468800           true          NaN           0   
580319184652890113          false          NaN           0   
580320684305416192     unverified          NaN           0   
580321156508577792          false          NaN           0   
580322453928431617          false          NaN           0   

                                                                 text  \
580319078155468800  Germanwings Airbus A320 crashes in French Alps...   
580319184652890113  BREAKING : 148 passengers were on board #Germa...   
580320684305416192  Accident aircraft looks to be Germanwings ( Ai...   
580321156508577792  Now hearing 148 passengers + crew on board the...   
580322453928431617  German Wings airline tweeting now about report...   

                         topic  opinion  isVulgar  \
580319078155468800        true        0     False   
580319184652890113       false        0     False   
580320684305416192  unverified        0     False   
580321156508577792       false        0     False   
580322453928431617       false        0     False   

                                                                  POS  \
580319078155468800  [(Germanwings, ^), (Airbus, ^), (A320, ^), (cr...   
580319184652890113  [(BREAKING, N), (:, ,), (148, $), (passengers,...   
580320684305416192  [(Accident, N), (aircraft, N), (looks, V), (to...   
580321156508577792  [(Now, R), (hearing, V), (148, $), (passengers...   
580322453928431617  [(German, A), (Wings, N), (airline, N), (tweet...   

                    wordCount  \
580319078155468800   4.555903   
580319184652890113  11.555903   
580320684305416192  11.555903   
580321156508577792  13.555903   
580322453928431617  12.555903   

                                                            posCounts  \
580319078155468800  [0, 0, 0, 6, 0, 0, 0, 1, 0, 0, 0, 0, 2, 0, 0, ...   
580319184652890113  [3, 0, 0, 4, 0, 0, 0, 3, 1, 0, 0, 2, 2, 0, 0, ...   
580320684305416192  [5, 0, 0, 4, 0, 0, 0, 2, 0, 0, 0, 0, 2, 1, 0, ...   
580321156508577792  [4, 0, 0, 2, 0, 0, 0, 3, 1, 1, 0, 1, 3, 1, 0, ...   
580322453928431617  [5, 0, 0, 2, 0, 0, 0, 2, 1, 1, 0, 0, 5, 0, 0, ...   

                    containsAdjective  containsURL  containsEmoji  \
580319078155468800              False         True          False   
580319184652890113               True         True          False   
580320684305416192              False         True          False   
580321156508577792               True        False          False   
580322453928431617               True         True          False   

                    containsAbbreviation  
580319078155468800                 False  
580319184652890113                 False  
580320684305416192                 False  
580321156508577792                 False  
580322453928431617                 False

In [9]:
for i, tag in enumerate(TwitterParser.tagset):
    tag_counts = []
    for pos_counts in df['posCounts']:
        tag_counts.append(pos_counts[i])
    column_name = 'num_' + tag
    df[column_name] = tag_counts
    normalize(column_name)
df.head()

classification context_path has_context  \
580319078155468800           true          NaN           0   
580319184652890113          false          NaN           0   
580320684305416192     unverified          NaN           0   
580321156508577792          false          NaN           0   
580322453928431617          false          NaN           0   

                                                                 text  \
580319078155468800  Germanwings Airbus A320 crashes in French Alps...   
580319184652890113  BREAKING : 148 passengers were on board #Germa...   
580320684305416192  Accident aircraft looks to be Germanwings ( Ai...   
580321156508577792  Now hearing 148 passengers + crew on board the...   
580322453928431617  German Wings airline tweeting now about report...   

                         topic  opinion  isVulgar  \
580319078155468800        true        0     False   
580319184652890113       false        0     False   
580320684305416192  unverified        0     False   
580321156508577792       false        0     False   
580322453928431617       false        0     False   

                                                                  POS  \
580319078155468800  [(Germanwings, ^), (Airbus, ^), (A320, ^), (cr...   
580319184652890113  [(BREAKING, N), (:, ,), (148, $), (passengers,...   
580320684305416192  [(Accident, N), (aircraft, N), (looks, V), (to...   
580321156508577792  [(Now, R), (hearing, V), (148, $), (passengers...   
580322453928431617  [(German, A), (Wings, N), (airline, N), (tweet...   

                    wordCount  \
580319078155468800   4.555903   
580319184652890113  11.555903   
580320684305416192  11.555903   
580321156508577792  13.555903   
580322453928431617  12.555903   

                                                            posCounts  ...    \
580319078155468800  [0, 0, 0, 6, 0, 0, 0, 1, 0, 0, 0, 0, 2, 0, 0, ...  ...     
580319184652890113  [3, 0, 0, 4, 0, 0, 0, 3, 1, 0, 0, 2, 2, 0, 0, ...  ...     
580320684305416192  [5, 0, 0, 4, 0, 0, 0, 2, 0, 0, 0, 0, 2, 1, 0, ...  ...     
580321156508577792  [4, 0, 0, 2, 0, 0, 0, 3, 1, 1, 0, 1, 3, 1, 0, ...  ...     
580322453928431617  [5, 0, 0, 2, 0, 0, 0, 2, 1, 1, 0, 0, 5, 0, 0, ...  ...     

                    num_X  num_Y     num_#     num_@  num_~     num_U  num_E  \
580319078155468800    0.0    0.0 -0.568624 -0.408248   -0.4  0.402784    0.0   
580319184652890113    0.0    0.0  0.431376 -0.408248   -0.4  0.402784    0.0   
580320684305416192    0.0    0.0  0.431376 -0.408248   -0.4  0.402784    0.0   
580321156508577792    0.0    0.0  0.431376  0.591752   -0.4 -0.597216    0.0   
580322453928431617    0.0    0.0 -0.568624  0.591752   -0.4  0.402784    0.0   

                       num_$     num_,  num_G  
580319078155468800 -0.840635 -2.135416   -0.2  
580319184652890113  0.159365 -1.135416   -0.2  
580320684305416192  1.159365  1.864584   -0.2  
580321156508577792  1.159365 -0.135416   -0.2  
580322453928431617  0.159365 -1.135416   -0.2  

[5 rows x 39 columns]

In [10]:
df.loc[df.classification == 'true', 'classification'] = 1
df.loc[df.classification == 'false', 'classification'] = 0
df.loc[df.classification == 'unverified', 'classification'] = 2


attributes = []
# getting the labels
# You have to comment this out if you want only tweet ID to be in the features. 
# Note that by doing this, you will screw up the simple/tr,simple/dev test located after this


attributes = ['isVulgar', 'containsAdjective', 'containsURL', 'containsEmoji', 'containsAbbreviation', 'wordCount']
for tag in TwitterParser.tagset:
    attributes.append('num_' + tag)
    
dev_labels = df['classification']
dev_labels = [l for l in dev_labels]
dev_labels = np.array(dev_labels)

# getting the values as a list of lists
dev_values = df[attributes].values.tolist()


#Below puts the tweet ID as a feature. Comment this out if you aren't using tweetID
###for i,index in enumerate(df.index):
###    dev_values[i].append(int(index))


dev_values = np.array(dev_values)
dev_values

array([[ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  4.55590279e+00,
        -2.03469899e+00, -4.08248290e-01,  0.00000000e+00,
         4.09649446e+00,  0.00000000e+00, -2.00000000e-01,
         0.00000000e+00, -1.15993937e-02, -7.78888096e-01,
        -5.00000000e-01,  0.00000000e+00, -9.00000000e-01,
         4.75751551e-01, -4.58257569e-01, -3.31662479e-01,
         0.00000000e+00,  0.00000000e+00, -5.68624070e-01,
        -4.08248290e-01, -4.00000000e-01,  4.02784238e-01,
         0.00000000e+00, -8.40634681e-01, -2.13541565e+00,
        -2.00000000e-01],
       [ 0.00000000e+00,  1.00000000e+00,  1.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  1.15559028e+01,
         9.65301005e-01, -4.08248290e-01,  0.00000000e+00,
         2.09649446e+00,  0.00000000e+00, -2.00000000e-01,
         0.00000000e+00,  1.98840061e+00,  2.21111904e-01,
        -5.00000000e-01,  0.00000000e+00,  1.10000000e+00,
         4.75751551e-01, -4.58

In [11]:
import classifiers

# note predict_proba() gets probabilities for all 3 labels
#... and decision_tree_classifier uses decision_function() instead of predict_proba()... weird sklearn quirk
# NOTE: This is where you change the classifier type. Can pick from [naive_bayes, svm_classifier, decision_tree_classifier]
predictions, probabilities = classifiers.decision_tree_classifier(dev_values, dev_labels, dev_values)

ps = []
for i, p in enumerate(predictions):
    if p == 0:
        ps.append('false')
    if p == 1:
        ps.append('true')
    if p == 2:
        ps.append('unverified')
    

# creates pairings of the prediction and the probability of the prediction
pred_probs_pairs = [[ps[i], probabilities[i][predictions[i]]] for i in range(len(predictions))]  

#now we make a dictionary of tweetID to the pred_probs_pairs
pred_dict = {index:pred_probs_pairs[i] for i,index in enumerate(df.index)}
pred_dict

{'580319078155468800': ['true', 1.0],
 '580319184652890113': ['false', 1.0],
 '580320684305416192': ['unverified', 1.0],
 '580321156508577792': ['false', 1.0],
 '580322453928431617': ['false', 1.0],
 '580323060533764097': ['true', 1.0],
 '580324027715063808': ['true', 1.0],
 '580325090367315968': ['unverified', 1.0],
 '580326222107951104': ['false', 1.0],
 '580331561398108160': ['false', 1.0],
 '580332109782466561': ['true', 1.0],
 '580333763512705025': ['false', 1.0],
 '580333909008871424': ['true', 1.0],
 '580339547269144576': ['false', 1.0],
 '580339825649291264': ['false', 1.0],
 '580340476949086208': ['false', 1.0],
 '580348081100734464': ['true', 1.0],
 '580360165540642816': ['false', 1.0],
 '580371845997682688': ['true', 1.0],
 '580882341880446977': ['true', 1.0],
 '581047170637381632': ['true', 1.0],
 '581063377226637312': ['true', 1.0],
 '581293286268129280': ['false', 1.0],
 '581386094337474560': ['unverified', 1.0],
 '581473088249958400': ['false', 1.0]}

In [13]:
with open('output/classifier_output/test.json', 'w') as outfile:
    json.dump(pred_dict, outfile)

In [14]:
## python3 scorer/score.py semeval2017-task8-dataset/traindev/rumoureval-subtaskB-dev.json output/classifier_output/test.json


## Training on simple/tr, testing on simple/dev


In [15]:
# Simply doing all of the transformations we did in the first few cells

tr_df = pd.read_pickle('output/simple/train_data_simple.pickle')

wordlist = VulgarExtractor.vulgarWords("badwords.txt") 
dftext = tr_df[['text']]
result = dftext.applymap(lambda x: VulgarExtractor.containsVulgar(x,wordlist))
tr_df['isVulgar'] = result

sys.path.insert(1, "./feature-extraction/twitter-features")
textlist = [txt.replace('\n','') for txt in tr_df['text'].tolist()]
tagged_sents = TwitterParser.tag(textlist)
tr_df['POS'] = tagged_sents

word_counts = [TwitterParser.word_count(tagged_line) for tagged_line in tr_df['POS']]
pos_count_list = [TwitterParser.pos_counts(tagged_line) for tagged_line in tr_df['POS']]
contains_adjs = [TwitterParser.contains_adjectives(tagged_line) for tagged_line in tr_df['POS']]
contains_urls = [TwitterParser.contains_url(tagged_line) for tagged_line in tr_df['POS']]
contains_emojis = [TwitterParser.contains_emoji(tagged_line) for tagged_line in tr_df['POS']]
contains_abbrevs = [TwitterParser.contains_abbreviation(tagged_line) for tagged_line in tr_df['POS']]

tr_df['wordCount'] = word_counts
tr_df['posCounts'] = pos_count_list
tr_df['containsAdjective'] = contains_adjs
tr_df['containsURL'] = contains_urls
tr_df['containsEmoji'] = contains_emojis
tr_df['containsAbbreviation'] = contains_abbrevs

for i, tag in enumerate(TwitterParser.tagset):
    tag_counts = []
    for pos_counts in tr_df['posCounts']:
        tag_counts.append(pos_counts[i])
    column_name = 'num_' + tag
    tr_df[column_name] = tag_counts

tr_df.head()

classification  \
498280126254428160     unverified   
498430783699554305           true   
499366666300846081     unverified   
499368931367608320     unverified   
499456140044824576     unverified   

                                                         context_path  \
498280126254428160                                                NaN   
498430783699554305                                                NaN   
499366666300846081                                                NaN   
499368931367608320                                                NaN   
499456140044824576  ./semeval2017-task8-dataset/rumoureval-data/fe...   

                   has_context  \
498280126254428160           0   
498430783699554305           0   
499366666300846081           0   
499368931367608320           0   
499456140044824576           1   

                                                                 text  \
498280126254428160  Mike Brown was staying with his grandmother fo...   
498430783699554305  Witness: Police allegedly stopped Mike Brown a...   
499366666300846081  Line of police cars with high beams on greets ...   
499368931367608320  Currently the #FoxNews website has zero, repea...   
499456140044824576  St. Louis Co Police tell me ofcr shot a man wh...   

                       topic  isVulgar  \
498280126254428160  ferguson     False   
498430783699554305  ferguson     False   
499366666300846081  ferguson     False   
499368931367608320  ferguson     False   
499456140044824576  ferguson     False   

                                                                  POS  \
498280126254428160  [(Mike, ^), (Brown, ^), (was, V), (staying, V)...   
498430783699554305  [(Witness, N), (:, ,), (Police, N), (allegedly...   
499366666300846081  [(Line, N), (of, P), (police, N), (cars, N), (...   
499368931367608320  [(Currently, R), (the, D), (#FoxNews, ^), (web...   
499456140044824576  [(St., ^), (Louis, ^), (Co, ^), (Police, ^), (...   

                    wordCount  \
498280126254428160         15   
498430783699554305         14   
499366666300846081         20   
499368931367608320         20   
499456140044824576         26   

                                                            posCounts  \
498280126254428160  [3, 1, 0, 2, 0, 0, 0, 3, 0, 0, 0, 3, 3, 0, 0, ...   
498430783699554305  [3, 1, 0, 2, 0, 0, 0, 3, 0, 1, 0, 0, 4, 0, 0, ...   
499366666300846081  [6, 0, 0, 1, 0, 1, 0, 5, 1, 0, 0, 1, 4, 0, 1, ...   
499368931367608320  [7, 0, 0, 3, 0, 0, 0, 1, 1, 2, 0, 2, 3, 0, 0, ...   
499456140044824576  [5, 3, 0, 6, 0, 0, 0, 2, 2, 0, 0, 1, 5, 1, 0, ...   

                    containsAdjective  ...    num_X  num_Y  num_#  num_@  \
498280126254428160              False  ...        0      0      1      0   
498430783699554305              False  ...        0      0      1      0   
499366666300846081               True  ...        0      0      0      0   
499368931367608320               True  ...        0      0      0      0   
499456140044824576               True  ...        0      0      1      0   

                    num_~  num_U  num_E  num_$  num_,  num_G  
498280126254428160      0      0      0      0      2      0  
498430783699554305      0      1      0      0      2      0  
499366666300846081      0      1      0      0      3      0  
499368931367608320      0      0      0      1      4      0  
499456140044824576      0      0      0      1      1      0  

[5 rows x 38 columns]

In [16]:
# Changes "true"/"false"/"unverified" to numeric values, just like the in the early cells

tr_df.loc[tr_df.classification == 'true', 'classification'] = 1
tr_df.loc[tr_df.classification == 'false', 'classification'] = 0
tr_df.loc[tr_df.classification == 'unverified', 'classification'] = 2
# getting the labels

attributes = ['isVulgar', 'containsAdjective', 'containsURL', 'containsEmoji', 'containsAbbreviation', 'wordCount']
for tag in TwitterParser.tagset:
    attributes.append('num_' + tag)

tr_labels = tr_df['classification']
tr_labels = [l for l in tr_labels]
tr_labels = np.array(tr_labels)


# getting the values as a list of lists
tr_values = tr_df[attributes].values.tolist()
tr_values = np.array(tr_values)

In [17]:
predictions, probabilities = classifiers.naive_bayes(tr_values, tr_labels, dev_values)
print(probabilities)
ps = []
for i, p in enumerate(predictions):
    if p == 0:
        ps.append('false')
    if p == 1:
        ps.append('true')
    if p == 2:
        ps.append('unverified')
    

# creates pairings of the prediction and the probability of the prediction
pred_probs_pairs = [[ps[i], probabilities[i][predictions[i]]] for i in range(len(predictions))]  


pred_dict = {index:pred_probs_pairs[i] for i,index in enumerate(df.index)}


pred_dict

[[4.89909754e-01 5.02308897e-01 7.78134923e-03]
 [5.38398212e-01 3.66645920e-01 9.49558679e-02]
 [1.05304264e-01 7.72600520e-01 1.22095217e-01]
 [5.84388298e-01 2.02928985e-01 2.12682717e-01]
 [2.18284158e-01 3.76246217e-01 4.05469625e-01]
 [2.78707690e-01 7.06115387e-01 1.51769233e-02]
 [5.22160648e-01 4.32444031e-01 4.53953202e-02]
 [1.78065102e-01 5.19671451e-01 3.02263447e-01]
 [3.15593807e-01 5.54301748e-01 1.30104445e-01]
 [1.00000000e+00 1.91536843e-14 1.39413306e-23]
 [6.74767375e-05 6.23549252e-08 9.99932461e-01]
 [2.64283029e-01 7.00554268e-01 3.51627035e-02]
 [3.23771881e-01 4.86062352e-01 1.90165768e-01]
 [2.35033535e-01 2.40858364e-01 5.24108101e-01]
 [3.63441039e-01 5.99083928e-01 3.74750331e-02]
 [4.04312065e-01 5.61897231e-01 3.37907041e-02]
 [2.75585819e-01 6.22852847e-01 1.01561334e-01]
 [1.61611079e-01 2.84643881e-01 5.53745040e-01]
 [1.48094345e-01 6.50278862e-01 2.01626792e-01]
 [2.15174016e-01 6.60964066e-01 1.23861919e-01]
 [3.82390134e-01 3.29508227e-01 2.881016

{'580319078155468800': ['true', 0.5023088965627981],
 '580319184652890113': ['false', 0.5383982120388475],
 '580320684305416192': ['true', 0.7726005198616951],
 '580321156508577792': ['false', 0.5843882977751353],
 '580322453928431617': ['unverified', 0.40546962532314773],
 '580323060533764097': ['true', 0.7061153869312328],
 '580324027715063808': ['false', 0.5221606483483459],
 '580325090367315968': ['true', 0.519671450670753],
 '580326222107951104': ['true', 0.5543017480344555],
 '580331561398108160': ['false', 0.9999999999999822],
 '580332109782466561': ['unverified', 0.9999324609075481],
 '580333763512705025': ['true', 0.7005542678091099],
 '580333909008871424': ['true', 0.4860623515470341],
 '580339547269144576': ['unverified', 0.5241081006674231],
 '580339825649291264': ['true', 0.5990839279538439],
 '580340476949086208': ['true', 0.5618972310360748],
 '580348081100734464': ['true', 0.6228528471598066],
 '580360165540642816': ['unverified', 0.5537450400510325],
 '5803718459976826

In [18]:
with open('output/classifier_output/tr_test.json', 'w') as outfile:
    json.dump(pred_dict, outfile)
    
#test with:
### python3 scorer/score.py semeval2017-task8-dataset/traindev/rumoureval-subtaskB-dev.json output/classifier_output/tr_test.json